added frontend and backend for incidents and cicd
Signed-off-by: Naresh chandanbatve <chandanbatven@gmail.com>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,8 +57,8 @@ jobs:
         env:
           DOCKER_REPO: ${{secrets.DOCKER_REPO}}
         run: |
-          docker build -t $DOCKER_REPO:backendv2 -f app/Dockerfile .
-          docker push $DOCKER_REPO:backendv2
+          docker build -t $DOCKER_REPO:backend-${{ env.IMAGE_TAG }} -f app/Dockerfile .
+          docker push $DOCKER_REPO:backend-${{ env.IMAGE_TAG }}
 
 
       - name: Build and Push Frontend Docker Image
@@ -66,34 +66,36 @@ jobs:
         env:
           DOCKER_REPO: ${{secrets.DOCKER_REPO}}
         run: |
-          docker build -t $DOCKER_REPO:frontendv3 ./frontend
-          docker push $DOCKER_REPO:frontendv3
+          docker build -t $DOCKER_REPO:frontend-${{ env.IMAGE_TAG }} ./frontend
+          docker push $DOCKER_REPO:frontend-${{ env.IMAGE_TAG }}
 
-      # - name: Update kubeconfig
-      #   if: env.cluster_exists == 'true'
-      #   run: |
-      #     aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
+      - name: Update kubeconfig
+        if: env.cluster_exists == 'true'
+        run: |
+          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
 
-      # - name: Install Helm
-      #   if: env.cluster_exists == 'true'
-      #   run: |
-      #       curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+      - name: Install Helm
+        if: env.cluster_exists == 'true'
+        run: |
+            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
             
-      # - name: Deploy with Helm
-      #   if: env.cluster_exists == 'true'
-      #   run: |
-      #     CURRENT_HOST=$(kubectl get ingress app-helm -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || echo "")
+      - name: Deploy with Helm
+        if: env.cluster_exists == 'true'
+        run: |
+          CURRENT_HOST=$(kubectl get ingress app-helm -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || echo "")
 
-      #     helm upgrade --install app ./helm \
-      #       --set ingress.enabled=true \
-      #       --set image.repository=$DOCKER_REPO \
-      #       --set image.tag=${{ env.IMAGE_TAG }} \
-      #       --set ingress.hosts[0].host="$CURRENT_HOST" \
-      #       --set ingress.tls[0].hosts[0]="$CURRENT_HOST" \
-      #       --set ingress.hosts[0].paths[0].path="/" \
-      #       --set ingress.hosts[0].paths[0].pathType=Prefix \
-      #       --set ingress.tls[0].secretName=app-tls
+          helm upgrade --install app ./helm \
+            --set ingress.enabled=true \
+            --set backend.image.repository=$DOCKER_REPO \
+            --set backend.image.tag=backend-${{ env.IMAGE_TAG }} \
+            --set frontend.image.repository=$DOCKER_REPO \
+            --set frontend.image.tag=frontend-${{ env.IMAGE_TAG }} \
+            --set ingress.hosts[0].host="$CURRENT_HOST" \
+            --set ingress.tls[0].hosts[0]="$CURRENT_HOST" \
+            --set ingress.hosts[0].paths[0].path="/" \
+            --set ingress.hosts[0].paths[0].pathType=Prefix \
+            --set ingress.tls[0].secretName=app-tls
             
-      # - name: Skip if cluster not available
-      #   if: env.cluster_exists == 'false'
-      #   run: echo "EKS cluster not found. Skipping deployment."
+      - name: Skip if cluster not available
+        if: env.cluster_exists == 'false'
+        run: echo "EKS cluster not found. Skipping deployment."
